version: '3.4'

services:
  testtaskdb:
    container_name: "Test-task-db"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password@1
    ports:
    - 8002:1433
  
  testtask:
    container_name: "Test-docker-task"
    image: ${DOCKER_REGISTRY-}testtask
    build:
      context: .
      dockerfile: TestTask/Dockerfile
    ports:
    - 8001:80
    depends_on:
    - testtaskdb
    environment:
    - DB_Host=testtaskdb
    - DB_Name=Test
    - DB_SA_PASSWORD=Password@1
